### ISSUE TITLE
Test using local action

### ISSUE THREAD

**Issue by kenorb** [FX31337/MQL-Tester-Action#4]
Convert Action@master and Action@dev into one file using local action, e.g.

```
    - name: Run Custom Docker Action
      uses: ./maven # local action
      with:
        args: clean
```

See: https://github.community/t5/GitHub-Actions/Custom-docker-action-mounted-volumes/td-p/39350
